MODEL:
  NAME: CVAE
  PRETRAIN: CLIPreid
  FEAT_FUSION: True
  LATENT_SIZE: 12  # 12, 36, 64
  FEATURE_DIM: 1280
  # ENCODER_LAYER_SIZES: [1280, 256]  # should be from 1280 to 12 
  # DECODER_LAYER_SIZES: [256, 1280]

TRAIN:
  OPTIMIZER:
    LR: 1e-4

LOSS:
  PAIR_LOSS: triplet
  PAIR_M: 0.3
TEST:
  START_EVAL: -1
TAG: clipreid_cvae_ce_trip