MODEL:
  NAME: CVAE
  PRETRAIN: CLIPreidNew  # CLIPreid or CLIPreidNew
  FEAT_FUSION: True
  LATENT_SIZE: 64  # 12, 36, 64
  FEATURE_DIM: 1280  # 768 for TransReID and 1280 for CLIPreid
  ZC_DIM: 128  # ori 128
  ZS_DIM: 64
  # ENCODER_LAYER_SIZES: [1280, 256]  # should be from 1280 to 12 
  # DECODER_LAYER_SIZES: [256, 1280]

TRAIN:
  MAX_EPOCH: 120
  OPTIMIZER:
    LR: 1e-3
    # 1e-4 for stage 1 and 1e-3 for stage2
    # 0.0001*10 = 0.001
    # 0.0001*5 = 0.0005 = 5e-4
  LR_SCHEDULER: 
    STEPSIZE: [60]


DATA:
  NUM_INSTANCES: 4
  TRAIN_BATCH: 64

LOSS:
  PAIR_LOSS: triplet
  PAIR_M: 0.3
TEST:
  START_EVAL: -1
TAG: clipreid_simplevae