MODEL:
  NAME: CVAE
  PRETRAIN: CLIPreid
  FEAT_FUSION: True
  LATENT_SIZE: 12
  FEATURE_DIM: 1280
  ENCODER_LAYER_SIZES: [1280, 256]
  DECODER_LAYER_SIZES: [256, 1280]
LOSS:
  CLA_LOSS: crossentropy
  PAIR_LOSS: triplet
  PAIR_M: 0.3
TAG: clipreid_cvae_ce_trip